version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven
      - apt-get -y install maven

  pre_build:
    commands:
      - echo Cloning the GitHub repository
      - git clone https://github.com/Venkypasala/E-commerce-project-springBoot.git
      - cd E-commerce-project-springBoot/JtProject/

  build:
    commands:
      - echo Building the Java application
      - mvn clean install

  post_build:
    commands:
      - echo Performing post-build actions
      - cd target/
      - java -jar "JtSpringProject-0.0.1-SNAPSHOT.jar"

artifacts:
  files:
    - E-commerce-project-springBoot/JtProject/target/JtSpringProject-0.0.1-SNAPSHOT.jar
  
